apiVersion: v1
kind: Service
metadata:
  name: nodejs-api-service-lb
  labels:
    app: nodejs-api
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 3000
  selector:
    app: nodejs-api