apiVersion: v1
kind: Service
metadata:
  name: nodejs-api-service
  labels:
    app: nodejs-api
spec:
  type: NodePort
  ports:
  - port: 3000
    targetPort: 3000
    nodePort: 30080
  selector:
    app: nodejs-api